export const LEGAL_BUSINESS_INFO = {
  ownerName: "Mesut Can",
  companyName: "Mesut Can (Şahıs İşletmesi)",
  brandName: "Can Antika",
  businessType: "Antika Perakende Ticareti",
  activityCode: "477901",
  taxType: "Yıllık Gelir Vergisi",
  taxOffice: "Beyoğlu",
  taxId: "62857430140",
  startDate: "01.03.2021",
  website: "www.canantika.com",
  address: "Hüseyinağa Mah. Meşrutiyet Cad. Avrupa Pasajı No: 8 İç Kapı No: 7 Beyoğlu / İstanbul",
  phone: "+90 507 687 92 15",
  email: "destek@canantika.com",
}
