package com.mehmetkerem.enums;

public enum AdminAction {
    PRODUCT_CREATED,
    PRODUCT_UPDATED,
    PRODUCT_DELETED,
    ORDER_STATUS_UPDATED,
    ORDER_CANCELLED,
    CATEGORY_CREATED,
    CATEGORY_UPDATED,
    CATEGORY_DELETED,
    COUPON_CREATED,
    COUPON_UPDATED,
    COUPON_DELETED,
    SETTINGS_UPDATED,
    USER_UPDATED,
    USER_DELETED,
    RETURN_APPROVED,
    RETURN_REJECTED,
    TICKET_RESPONDED,
    FAQ_CREATED,
    FAQ_UPDATED,
    FAQ_DELETED,
    PAGE_CREATED,
    PAGE_UPDATED,
    PAGE_DELETED
}
